
apiVersion: v1
kind: Service
metadata:
  name: {{ include "amunchain.fullname" . }}
  labels:
    app: {{ include "amunchain.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "amunchain.fullname" . }}
  ports:
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
