apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-hostpath-volumes
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: block-hostpath
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "hostPath volumes are forbidden (Enterprise hard lock)."
        foreach:
          - list: "request.object.spec.volumes[]"
            deny:
              conditions:
                any:
                  - key: "{{ element.hostPath }}"
                    operator: NotEquals
                    value: null
