apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-explicit-runas-user-group
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-pod-runas-user-group
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "Pod spec.securityContext must explicitly set runAsUser and runAsGroup (non-root) and runAsNonRoot=true."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
              runAsUser: ">0"
              runAsGroup: ">0"
