apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-seccomp-nonroot
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-seccomp-runtime-default
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "seccompProfile RuntimeDefault is required."
        pattern:
          spec:
            securityContext:
              seccompProfile:
                type: "RuntimeDefault"
    - name: require-run-as-nonroot
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: "runAsNonRoot=true is required."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
            containers:
              - securityContext:
                  runAsNonRoot: true
