apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: amunchain-vault-spc
  namespace: amunchain
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.example.com"
    roleName: "amunchain"
    objects: |
      - objectName: "kv/data/amunchain/tls"
        objectType: "secret"
        objectVersion: ""
